name: Deployment

on:
  push:
    branches: [ main ]

jobs: 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
        
    - name: Build and Push image to Yandex
      env:
        YANDEX_ID: ${{ secrets.YANDEX_ID }}
        YANDEX_PUBLIC_KEY: ${{ secrets. YANDEX_PUBLIC_KEY }}
        YANDEX_KEY_ALGORITHM: ${{ secrets.YANDEX_KEY_ALGORITHM }}
        YANDEX_CREATED_AT: ${{ secrets.YANDEX_CREATED_AT }}
        YANDEX_SERVICE_ACCOUNT_ID: ${{ secrets.YANDEX_SERVICE_ACCOUNT_ID }}
        YANDEX_PRIVATE_KEY: ${{ secrets.YANDEX_PRIVATE_KEY }}
        YANDEX_REGISTRY_URL: ${{ secrets.YANDEX_REGISTRY_URL }}

      run: |
        python .github/workflows/yandex/build.py